### ISSUE TITLE
Ugrade the package_info_plus version

### ISSUE THREAD

**Issue by rahmanrezaee** [kamranbekirovyz/versionarte#5]
I am using both packages in project and I'm not able to use the last version of package_info_plus

**Comment by kamranbekirovyz** [comment]
Hi. Thanks for opening the issue. Which version of `package_info_plus` do you use in your project?

**Comment by rahmanrezaee** [comment]
package_info_plus: 8.0.0

**Comment by kamranbekirovyz** [comment]
Oh, I see. I'll merge your PR ASAP

**Comment by elliotrtd** [comment]
@kamranbekirovyz  would be great to get this updated soon - it also creates conflicts with other packages which rely on a newer version.

e.g. 
`Because wakelock_plus 1.2.5 depends on package_info_plus >=6.0.0 <9.0.0 and versionarte >=0.9.1 depends on package_info_plus ^5.0.1, wakelock_plus 1.2.5 is incompatible with versionarte >=0.9.1.
So, because timing_app depends on both versionarte ^1.0.0 and wakelock_plus 1.2.5, version solving failed.`

**Comment by kamranbekirovyz** [comment]
@elliotrtd thanks for using the package. There is one PR that I'm planning to merge to the main. After that I'll release version 1.1.0. It should happen today or tomorrow.

**Comment by kamranbekirovyz** [comment]
I've already upgraded all the dependencies to their latest version. I'll be publishing a new version tomorrow.

**Comment by kamranbekirovyz** [comment]
🎆 versionarte 1.1.0 published with newer dependencies on the pubspec.yaml 

Does that solve your issue, @rahmanrezaee ?
